export const style = {};
// export const style = {
//   activeCellBackgroundColor: '#1e1e20',
//   activeCellBorderColor: '#1e1e20',
//   activeCellBorderWidth: 0.25,
//   activeCellColor: '#d9cb9e',
//   activeCellFont: '16px sans-serif',
//   activeCellHoverBackgroundColor: '#374140',
//   activeCellHorizontalAlignment: 'left',
//   activeCellHoverColor: '#374140',
//   activeCellOverlayBorderColor: '#dc3522',
//   activeCellOverlayBorderWidth: 1.25,
//   activeCellPaddingBottom: 5,
//   activeCellPaddingLeft: 5,
//   activeCellPaddingRight: 7,
//   activeCellPaddingTop: 5,
//   activeCellSelectedBackgroundColor: '#374140',
//   activeCellSelectedColor: '#d9cb9e',
//   activeCellVerticalAlignment: 'center',
//   activeColumnHeaderCellBackgroundColor: '#2a2c2b',
//   activeColumnHeaderCellColor: '#d9cb9e',
//   activeRowHeaderCellBackgroundColor: '#2a2c2b',
//   activeRowHeaderCellColor: '#d9cb9e',
//   autocompleteBottomMargin: 60,
//   autosizeHeaderCellPadding: 8,
//   autosizePadding: 5,
//   cellAutoResizePadding: 13,
//   cellBackgroundColor: '#1e1e20',
//   cellBorderColor: '#2a2c2b',
//   cellBorderWidth: 0.25,
//   cellColor: '#d9cb9e',
//   cellFont: '16px sans-serif',
//   cellGridHeight: '250',
//   cellHeight: 24,
//   cellHeightWithChildGrid: 150,
//   cellHorizontalAlignment: 'left',
//   cellHoverBackgroundColor: '#2a2c2b',
//   cellHoverColor: '#2a2c2b',
//   cellPaddingBottom: 5,
//   cellPaddingLeft: 5,
//   cellPaddingRight: 7,
//   cellPaddingTop: 5,
//   cellSelectedBackgroundColor: '#374140',
//   cellSelectedColor: '#d9cb9e',
//   cellVerticalAlignment: 'center',
//   cellWidth: 250,
//   cellWidthWithChildGrid: 250,
//   cellWhiteSpace: 'nowrap',
//   cellLineHeight: '1',
//   cellLineSpacing: '3',
//   childContextMenuArrowColor: 'rgba(43, 48, 43, 1)',
//   childContextMenuArrowHTML: '&#x25BA;',
//   childContextMenuMarginLeft: -5,
//   childContextMenuMarginTop: 0,
//   columnHeaderCellBackgroundColor: '#1e1e20',
//   columnHeaderCellBorderColor: '#1e1e20',
//   columnHeaderCellBorderWidth: 0.25,
//   columnHeaderCellCapBackgroundColor: 'rgba(240, 240, 240, 1)',
//   columnHeaderCellCapBorderColor: 'rgba(172, 172, 172, 1)',
//   columnHeaderCellCapBorderWidth: '1',
//   columnHeaderCellColor: '#d9cb9e',
//   columnHeaderCellFont: '16px sans-serif',
//   columnHeaderCellHeight: 25,
//   columnHeaderCellHorizontalAlignment: 'left',
//   columnHeaderCellHoverBackgroundColor: '#2a2c2b',
//   columnHeaderCellHoverColor: '#d9cb9e',
//   columnHeaderCellPaddingBottom: 5,
//   columnHeaderCellPaddingLeft: 5,
//   columnHeaderCellPaddingRight: 7,
//   columnHeaderCellPaddingTop: 5,
//   columnHeaderCellVerticalAlignment: 'center',
//   columnHeaderOrderByArrowBorderColor: 'rgba(195, 199, 202, 1)',
//   columnHeaderOrderByArrowBorderWidth: 1,
//   columnHeaderOrderByArrowColor: 'rgba(155, 155, 155, 1)',
//   columnHeaderOrderByArrowHeight: 8,
//   columnHeaderOrderByArrowMarginLeft: 0,
//   columnHeaderOrderByArrowMarginRight: 5,
//   columnHeaderOrderByArrowMarginTop: 6,
//   columnHeaderOrderByArrowWidth: 13,
//   contextFilterButtonBorder: 'solid 1px rgba(158, 163, 169, 1)',
//   contextFilterButtonBorderRadius: '3px',
//   contextFilterButtonHTML: '&#x25BC;',
//   contextFilterInputBackground: 'rgba(255,255,255,1)',
//   contextFilterInputBorder: 'solid 1px rgba(158, 163, 169, 1)',
//   contextFilterInputBorderRadius: '0',
//   contextFilterInputColor: 'rgba(0,0,0,1)',
//   contextFilterInputFontFamily: 'sans-serif',
//   contextFilterInputFontSize: '14px',
//   contextFilterInvalidRegExpBackground: 'rgba(180, 6, 1, 1)',
//   contextFilterInvalidRegExpColor: 'rgba(255, 255, 255, 1)',
//   contextMenuArrowColor: 'rgba(43, 48, 43, 1)',
//   contextMenuArrowDownHTML: '&#x25BC;',
//   contextMenuArrowUpHTML: '&#x25B2;',
//   contextMenuBackground: 'rgba(240, 240, 240, 1)',
//   contextMenuBorder: 'solid 1px rgba(158, 163, 169, 1)',
//   contextMenuBorderRadius: '3px',
//   contextMenuChildArrowFontSize: '12px',
//   contextMenuColor: 'rgba(43, 48, 43, 1)',
//   contextMenuCursor: 'default',
//   contextMenuFilterButtonFontFamily: 'sans-serif',
//   contextMenuFilterButtonFontSize: '10px',
//   contextMenuFilterInvalidExpresion: 'rgba(237, 155, 156, 1)',
//   contextMenuFontFamily: 'sans-serif',
//   contextMenuFontSize: '16px',
//   contextMenuHoverBackground: 'rgba(182, 205, 250, 1)',
//   contextMenuHoverColor: 'rgba(43, 48, 153, 1)',
//   contextMenuItemBorderRadius: '3px',
//   contextMenuItemMargin: '2px',
//   contextMenuLabelDisplay: 'inline-block',
//   contextMenuLabelMargin: '0 3px 0 0',
//   contextMenuLabelMaxWidth: '700px',
//   contextMenuLabelMinWidth: '75px',
//   contextMenuMarginLeft: 3,
//   contextMenuMarginTop: -3,
//   contextMenuOpacity: '0.98',
//   contextMenuPadding: '2px',
//   contextMenuWindowMargin: 6,
//   contextMenuZIndex: '10000',
//   cornerCellBackgroundColor: '#2a2c2b',
//   cornerCellBorderColor: '#1e1e20',
//   debugBackgroundColor: 'rgba(0, 0, 0, .0)',
//   debugColor: 'rgba(255, 15, 24, 1)',
//   debugEntitiesColor: 'rgba(76, 231, 239, 1.00)',
//   debugFont: '11px sans-serif',
//   debugPerfChartBackground: 'rgba(29, 25, 26, 1.00)',
//   debugPerfChartTextColor: 'rgba(255, 255, 255, 0.8)',
//   debugPerformanceColor: 'rgba(252, 255, 37, 1.00)',
//   debugScrollHeightColor: 'rgba(248, 33, 103, 1.00)',
//   debugScrollWidthColor: 'rgba(66, 255, 27, 1.00)',
//   debugTouchPPSXColor: 'rgba(246, 102, 24, 1.00)',
//   debugTouchPPSYColor: 'rgba(186, 0, 255, 1.00)',
//   display: 'undefined',
//   editCellBackgroundColor: 'white',
//   editCellBorder: 'solid 1px rgba(110, 168, 255, 1)',
//   editCellBoxShadow: '0 2px 5px rgba(0,0,0,0.4)',
//   editCellColor: 'black',
//   editCellFontFamily: 'sans-serif',
//   editCellFontSize: '16px',
//   editCellPaddingLeft: 4,
//   editCellZIndex: '10000',
//   frozenMarkerHoverColor: 'rgba(236, 243, 255, 1)',
//   frozenMarkerHoverBorderColor: 'rgba(110, 168, 255, 1)',
//   frozenMarkerActiveColor: 'rgba(236, 243, 255, 1)',
//   frozenMarkerActiveBorderColor: 'rgba(110, 168, 255, 1)',
//   frozenMarkerColor: 'rgba(222, 222, 222, 1)',
//   frozenMarkerBorderColor: 'rgba(168, 168, 168, 1)',
//   frozenMarkerBorderWidth: '1',
//   frozenMarkerWidth: '2',
//   gridBackgroundColor: '#1e1e20',
//   gridBorderCollapse: 'collapse',
//   gridBorderColor: '#2a2c2b',
//   gridBorderWidth: 1,
//   height: '100%',
//   maxHeight: 'undefined',
//   maxWidth: 'undefined',
//   minColumnWidth: 45,
//   minHeight: 24,
//   minRowHeight: 24,
//   minWidth: 'undefined',
//   mobileContextMenuMargin: '10',
//   mobileEditInputHeight: '30',
//   mobileEditFontFamily: 'sans-serif',
//   mobileEditFontSize: '16px',
//   moveOverlayBorderWidth: '1',
//   moveOverlayBorderColor: 'rgba(66, 133, 244, 1)',
//   moveOverlayBorderSegments: '12,7',
//   name: 'sea wolf',
//   overflowY: 'undefined',
//   overflowX: 'undefined',
//   reorderMarkerBackgroundColor: '#dc3522',
//   reorderMarkerBorderColor: '#dc3522',
//   reorderMarkerBorderWidth: 1.25,
//   reorderMarkerIndexBorderColor: '#dc3522',
//   reorderMarkerIndexBorderWidth: 2.75,
//   rowHeaderCellBackgroundColor: '#2a2c2b',
//   rowHeaderCellBorderColor: '#1e1e20',
//   rowHeaderCellBorderWidth: 0.25,
//   rowHeaderCellColor: '#d9cb9e',
//   rowHeaderCellFont: '16px sans-serif',
//   rowHeaderCellHeight: 25,
//   rowHeaderCellHorizontalAlignment: 'left',
//   rowHeaderCellHoverBackgroundColor: '#2a2c2b',
//   rowHeaderCellHoverColor: '#d9cb9e',
//   rowHeaderCellPaddingBottom: 5,
//   rowHeaderCellPaddingLeft: 5,
//   rowHeaderCellPaddingRight: 5,
//   rowHeaderCellPaddingTop: 5,
//   rowHeaderCellSelectedBackgroundColor: '#2a2c2b',
//   rowHeaderCellSelectedColor: '#d9cb9e',
//   rowHeaderCellVerticalAlignment: 'center',
//   rowHeaderCellWidth: 57,
//   scrollBarActiveColor: '#374140',
//   scrollBarBackgroundColor: '#1e1e20',
//   scrollBarBorderColor: '#1e1e20',
//   scrollBarBorderWidth: 0.5,
//   scrollBarBoxBorderRadius: 3,
//   scrollBarBoxColor: '#2a2c2b',
//   scrollBarBoxMargin: 2,
//   scrollBarBoxMinSize: 15,
//   scrollBarBoxWidth: 8,
//   scrollBarCornerBackgroundColor: '#2a2c29',
//   scrollBarCornerBorderColor: '#364036',
//   scrollBarWidth: 11,
//   selectionHandleBorderColor: 'rgba(255, 255, 255, 1)',
//   selectionHandleBorderWidth: '1.5',
//   selectionHandleColor: 'rgba(66, 133, 244, 1)',
//   selectionHandleSize: '8',
//   selectionHandleType: 'square',
//   selectionOverlayBorderColor: '#dc3522',
//   selectionOverlayBorderWidth: 1.25,
//   treeArrowBorderColor: '#2a2c2b',
//   treeArrowBorderWidth: 1,
//   treeArrowClickRadius: 5,
//   treeArrowColor: '#dc3522',
//   treeArrowHeight: 8,
//   treeArrowMarginLeft: 0,
//   treeArrowMarginRight: 5,
//   treeArrowMarginTop: 6,
//   treeArrowWidth: 13,
//   treeGridHeight: 250,
//   width: '100%'
// };
